.PHONY: core-audit regression paper experiment-A1 experiment-D experiment-C \
        competition donor-bootstrap full-readout ref-frame-figure \
        perturbation-figure decomposition-figure reproduction-dag
PYTHON ?= python3
GPU ?= 0

# The single canonical donor registry (exclusion-fixed) is the source of truth
# for every headline number in the paper. Its SHA-256 is:
#   9170a53026ab3263b451a3632a9e02318745acabf12f0b679921477afbefa301
# and is regenerated by scripts/build_canonical_panel.py.
# `make core-audit` rebuilds paper_numbers.json from canonical per-item
# hypotheses and verifies the headline against the canonical cells. The earlier
# pre-exclusion materialization (PURE 23.79 / gap +11.01) is reported only as a
# sensitivity analysis in SI~Sup.~N and is NOT reproduced by this target.

core-audit: regression paper check-paper
	@$(PYTHON) -c "import json; d=json.load(open('results/paper_numbers.json')); h=d['headline']; print('canonical headline: GT %.2f  PURE %.2f  gap %+.2f  CI %s' % (h['gt'], h['pure'], h['gap'], h.get('bootstrap_ci'))); assert abs(h['pure']-23.02)<0.05 and abs(h['gap']-10.24)<0.05, 'canonical headline mismatch'; print('core-audit PASS: headline matches canonical 23.02/+10.24')"

regression:
	@$(PYTHON) -c "import tests.test_checkpoint_gt_alignment as t; t.test_every_transfer_cell_uses_its_evaluators_local_gt(); print('checkpoint-GT alignment PASS')"

paper:
	$(PYTHON) scripts/build_paper_numbers.py
	@echo "Paper numbers written to results/paper_numbers.json"
	@echo "Compare with paper/main_lre.tex values for consistency."

# TeX value assertions (CI): cross-check headline numbers in main_lre.tex
# against the canonical paper_numbers.json. Extend CHECKS in the script as
# the paper matures.
check-paper: paper
	$(PYTHON) scripts/check_paper_numbers.py

# ---- Reviewer round-2 experiments (this revision) ----

# Experiment A1: released-checkpoint weight perturbation at competence parity
# (reviewer R2-1 confound). ~15 min on one GPU.
experiment-A1:
	$(PYTHON) scripts/e_released_perturbation.py --gpu $(GPU)
	$(PYTHON) scripts/make_figure_perturbation.py

# Experiment D: epoch-checkpoint decoupling search across rescue/long-schedule
# intermediate checkpoints. ~10 min on one GPU.
experiment-D:
	$(PYTHON) scripts/e_epoch_decouple.py --gpu $(GPU)

# Experiment C: per-item gap decomposition (OLS regression on lexical/template/
# signer/length features). CPU-only, ~1 min.
experiment-C:
	$(PYTHON) scripts/e_per_item_decomposition.py

# Uniform full-7060 readout for all reconstruction/distillation/rescue
# checkpoints (reviewer R2-5). ~30 min across 8 GPUs if run in parallel.
full-readout:
	@echo "Run e_full_readout.py across GPUs; see README for the 8-way launcher."
	$(PYTHON) scripts/e_full_readout.py --gpu $(GPU) \
	    --ckpt-dir checkpoints/reconstructions/seed_101 || true

# Donor reuse stats + donor-cluster bootstrap (reviewer R2-4). CPU, ~2 min.
donor-bootstrap:
	$(PYTHON) scripts/e_donor_cluster_bootstrap.py

# Reference-frame paired per-item figure (reviewer R2-6). CPU, ~1 min.
ref-frame-figure:
	$(PYTHON) scripts/make_figure_ref_frame_paired.py

# Competition-system ranking (reviewer R2-3 option a). Pending per-team pose
# outputs being placed in data/competition_systems/.
competition:
	$(PYTHON) scripts/competition_ranking.py --gpu $(GPU)

# Aggregate all round-2 experiments (CPU-only ones; A1/D/full-readout need GPU
# and are run individually above).
round2-all: donor-bootstrap ref-frame-figure experiment-C paper
	@echo "Round-2 CPU experiments complete. Run experiment-A1, experiment-D, full-readout on a GPU."

# Full reproduction DAG: decode + score all canonical evaluators from checkpoints.
# Requires model checkpoints and training data. See README for data setup.
reproduction-dag:
	$(PYTHON) scripts/build_canonical_panel.py
	$(PYTHON) scripts/build_paper_numbers.py
	@echo "reproduction-dag complete: canonical panel + paper numbers regenerated."
