.PHONY: core-audit regression paper experiment-A1 experiment-D experiment-C \
        competition donor-bootstrap full-readout ref-frame-figure \
        perturbation-figure decomposition-figure reproduction-dag \
        probe-multiplicity install-audit check-consistency
PYTHON ?= python3
GPU ?= 0

# TERMINOLOGY NOTE: In the paper, "GT" (ground truth) is called "REC" (recorded
# test poses) to avoid implying semantic gold-standard status. In the code,
# Makefile, and JSON keys, "GT" is retained as a legacy variable name and
# always refers to the REC condition (recorded test poses decoded by the BT
# recognizer). The mapping is: code GT == paper REC.

# The single canonical donor registry (exclusion-fixed) is the source of truth
# for every headline number in the paper. Its SHA-256 is:
#   9170a53026ab3263b451a3632a9e02318745acabf12f0b679921477afbefa301
# and is regenerated by scripts/build_canonical_panel.py.
# `make core-audit` recomputes selected reported statistics from committed
# per-item decodes and verifies the headline against the canonical cells.
# It does NOT retrain models, decode from checkpoints, or verify every number
# in the paper. Full reproduction requires the training bundle (L3/L4).
# The earlier pre-exclusion materialization (PURE 23.79 / gap +11.01) is
# reported only as a sensitivity analysis in SI~Sup.~N and is NOT reproduced.

# ---- Setup ----
# For L1 audit on a fresh Linux container, install ONLY requirements-audit.txt
# (4 packages: numpy, scipy, sacrebleu, pyyaml). The full requirements.lock.txt
# pins 236 packages including training/LLM tooling needed only for L3/L4.
install-audit:
	$(PYTHON) -m pip install -r requirements-audit.txt

# Verify the paper's headline counts/ranges against the disk-scanned registry.
# Layout-aware (works in both RCP working repo and this artifact mirror).
check-consistency:
	$(PYTHON) scripts/check_paper_consistency.py

core-audit: regression paper check-paper
	@$(PYTHON) -c "import json; d=json.load(open('results/paper_numbers.json')); h=d['headline']; print('canonical headline: GT %.2f  PURE %.2f  gap %+.2f  CI %s' % (h['gt'], h['pure'], h['gap'], h.get('bootstrap_ci'))); assert abs(h['pure']-23.02)<0.05 and abs(h['gap']-10.24)<0.05, 'canonical headline mismatch'; print('core-audit PASS: headline matches canonical 23.02/+10.24')"

regression:
	@$(PYTHON) -c "import tests.test_checkpoint_gt_alignment as t; t.test_every_transfer_cell_uses_its_evaluators_local_gt(); print('checkpoint-GT alignment PASS')"

paper:
	$(PYTHON) scripts/build_paper_numbers.py
	@echo "Paper numbers written to results/paper_numbers.json"
	@echo "Compare with paper/main_lre.tex values for consistency."

# TeX value assertions (CI): cross-check headline numbers in main_lre.tex
# against the canonical paper_numbers.json. Extend CHECKS in the script as
# the paper matures.
check-paper: paper
	$(PYTHON) scripts/check_paper_numbers.py

# ---- Reviewer round-2 experiments (this revision) ----

# Experiment A1: released-checkpoint weight perturbation at competence parity
# (reviewer R2-1 confound). ~15 min on one GPU.
experiment-A1:
	$(PYTHON) scripts/e_released_perturbation.py --gpu $(GPU)
	$(PYTHON) scripts/make_figure_perturbation.py

# Experiment D: epoch-checkpoint decoupling search across rescue/long-schedule
# intermediate checkpoints. ~10 min on one GPU.
experiment-D:
	$(PYTHON) scripts/e_epoch_decouple.py --gpu $(GPU)

# Experiment C: per-item gap decomposition (OLS regression on lexical/template/
# signer/length features). CPU-only, ~1 min.
experiment-C:
	$(PYTHON) scripts/e_per_item_decomposition.py

# Uniform full-7060 readout for all reconstruction/distillation/rescue
# checkpoints (reviewer R2-5). ~30 min across 8 GPUs if run in parallel.
full-readout:
	@echo "Run e_full_readout.py across GPUs; see README for the 8-way launcher."
	$(PYTHON) scripts/e_full_readout.py --gpu $(GPU) \
	    --ckpt-dir checkpoints/reconstructions/seed_101 || true

# Donor reuse stats + donor-cluster bootstrap (reviewer R2-4). CPU, ~2 min.
donor-bootstrap:
	$(PYTHON) scripts/e_donor_cluster_bootstrap.py

# Reference-frame paired per-item figure (reviewer R2-6). CPU, ~1 min.
ref-frame-figure:
	$(PYTHON) scripts/make_figure_ref_frame_paired.py

# Competition-system ranking (reviewer R2-3 option a). Pending per-team pose
# outputs being placed in data/competition_systems/.
competition:
	$(PYTHON) scripts/competition_ranking.py --gpu $(GPU)

# Aggregate all round-2 experiments (CPU-only ones; A1/D/full-readout need GPU
# and are run individually above).
round2-all: donor-bootstrap ref-frame-figure experiment-C paper
	@echo "Round-2 CPU experiments complete. Run experiment-A1, experiment-D, full-readout on a GPU."

# ---- Round-6 additions (probe multiplicity, donor-pool matching, accounting) ----

# Probe multiplicity: re-runs the 8-probe gap panel and selects the headline
# probe. CPU, ~10s. Regenerates results/probe_multiplicity.json.
probe-multiplicity:
	$(PYTHON) scripts/e_probe_multiplicity.py

# NOTE on accounting regeneration:
# scripts/build_accounting_table.py and the registry builder live in the RCP
# primary repo; this mirror carries the canonical outputs
# (results/canonical_checkpoint_registry.json, results/accounting_table.json,
# results/paper_numbers.json). Current counts (registry v5): 76 trained /
# 74 decoded / 73 unique binaries / 69 non-degenerate, all 69 gaps negative
# (range [-2.80, -0.21]); headline verified in CI via check_paper_numbers.py
# string assertions against paper/main_lre.tex, and the faithful-family block
# in results/paper_numbers.json (dev 11.59-12.62, readout 11.45-12.08,
# gaps [-2.80, -1.37], 8/8 negative). For full per-run regeneration, see the
# RCP primary repo (github.com/JiXin424/slrtp2025-replay-audit).

# Full reproduction DAG: decode + score all canonical evaluators from checkpoints.
# Requires model checkpoints and training data. See README for data setup.
reproduction-dag:
	$(PYTHON) scripts/build_canonical_panel.py
	$(PYTHON) scripts/build_paper_numbers.py
	@echo "reproduction-dag complete: canonical panel + paper numbers regenerated."

# ---- PDF build (clean, warning-checked) ----
# Builds main_lre.pdf and supplementary.pdf from paper/ sources.
# The supplementary uses xr-hyper \externaldocument{main_lre}; a filtered copy
# of main_lre.aux (without \bibcite lines) is used so the imported citations
# do not collide with the supplementary's own bibliography keys.
paper-pdf:
	cd paper && rm -f main_lre.aux main_lre.bbl main_lre.blg supplementary.aux supplementary.bbl supplementary.blg
	cd paper && grep -v '\\bibcite' main_lre.aux > main_lre_xr.aux 2>/dev/null || true
	cd paper && pdflatex -interaction=nonstopmode main_lre.tex > /dev/null && bibtex main_lre > /dev/null && pdflatex -interaction=nonstopmode main_lre.tex > /dev/null && pdflatex -interaction=nonstopmode main_lre.tex > /dev/null
	cd paper && grep -v '\\bibcite' main_lre.aux > main_lre_xr.aux
	cd paper && pdflatex -interaction=nonstopmode supplementary.tex > /dev/null && bibtex supplementary > /dev/null && pdflatex -interaction=nonstopmode supplementary.tex > /dev/null && pdflatex -interaction=nonstopmode supplementary.tex > /dev/null
	@cd paper && echo "--- main_lre warnings:" && (grep -cE "multiply defined|undefined" main_lre.log || true) && echo "--- supplementary warnings:" && (grep -cE "multiply defined|undefined" supplementary.log || true)
